import { Prisma } from "@prisma/client";
import type { AuthorizationContext } from "../security/authorization";
import { requireAuthorization } from "../security/authorization";
import { db } from "../db";
import { InventoryValidationError } from "./inventory";

export class InventoryAutomationService {
 async consumeReservation(context:AuthorizationContext,input:{organizationId:string;reservationId:string;reason:string;occurredAt:Date}){
  requireAuthorization(context,{organizationId:input.organizationId,permission:"inventory.manage"});
  const reason=input.reason.trim();if(!reason)throw new InventoryValidationError("Consumption reason is required");if(Number.isNaN(input.occurredAt.getTime()))throw new InventoryValidationError("Consumption time is invalid");
  return db.$transaction(async tx=>{
   const reservation=(await tx.$queryRaw<Array<{id:string;materialLotId:string;siteId:string|null;departmentId:string|null;quantity:string;unitOfMeasure:string;status:string}>>(Prisma.sql`SELECT id,"materialLotId","siteId","departmentId",quantity,"unitOfMeasure",status FROM "InventoryReservation" WHERE "organizationId"=${input.organizationId}::uuid AND id=${input.reservationId}::uuid FOR UPDATE`))[0];
   if(!reservation||reservation.status!=="ACTIVE")throw new InventoryValidationError("Active reservation not found");
   const lot=(await tx.$queryRaw<Array<{status:string;expirationDate:Date|null}>>(Prisma.sql`SELECT status,"expirationDate" FROM "MaterialLot" WHERE "organizationId"=${input.organizationId}::uuid AND id=${reservation.materialLotId}::uuid FOR UPDATE`))[0];
   if(!lot||lot.status!=="ACCEPTED")throw new InventoryValidationError("Reserved lot is no longer usable");const today=new Date(new Date().toISOString().slice(0,10));if(lot.expirationDate&&lot.expirationDate<today)throw new InventoryValidationError("Expired reserved lot cannot be consumed");
   const balance=(await tx.$queryRaw<Array<{quantityOnHand:string;unitOfMeasure:string}>>(Prisma.sql`SELECT "quantityOnHand","unitOfMeasure" FROM "InventoryBalance" WHERE "organizationId"=${input.organizationId}::uuid AND "materialLotId"=${reservation.materialLotId}::uuid AND "siteId" IS NOT DISTINCT FROM ${reservation.siteId}::uuid AND "departmentId" IS NOT DISTINCT FROM ${reservation.departmentId}::uuid FOR UPDATE`))[0];
   if(!balance||balance.unitOfMeasure!==reservation.unitOfMeasure||Number(balance.quantityOnHand)<Number(reservation.quantity))throw new InventoryValidationError("Insufficient physical inventory to fulfill reservation");
   await tx.$executeRaw(Prisma.sql`UPDATE "InventoryBalance" SET "quantityOnHand"="quantityOnHand"-${Number(reservation.quantity)},"updatedAt"=CURRENT_TIMESTAMP WHERE "organizationId"=${input.organizationId}::uuid AND "materialLotId"=${reservation.materialLotId}::uuid AND "siteId" IS NOT DISTINCT FROM ${reservation.siteId}::uuid AND "departmentId" IS NOT DISTINCT FROM ${reservation.departmentId}::uuid`);
   const transaction=(await tx.$queryRaw<Array<{id:string}>>(Prisma.sql`INSERT INTO "InventoryTransaction" ("organizationId","materialLotId","transactionType",quantity,"unitOfMeasure","siteId","departmentId",reason,"referenceKey","actorUserId","occurredAt") VALUES (${input.organizationId}::uuid,${reservation.materialLotId}::uuid,'CONSUMPTION'::"InventoryTransactionType",${Number(reservation.quantity)},${reservation.unitOfMeasure},${reservation.siteId}::uuid,${reservation.departmentId}::uuid,${reason},${`reservation:${reservation.id}`},${context.userId}::uuid,${input.occurredAt}) RETURNING id`))[0];if(!transaction)throw new InventoryValidationError("Reservation consumption could not be recorded");
   await tx.$executeRaw(Prisma.sql`UPDATE "InventoryReservation" SET status='CONSUMED',"consumedAt"=CURRENT_TIMESTAMP,"consumptionTransactionId"=${transaction.id}::uuid WHERE "organizationId"=${input.organizationId}::uuid AND id=${reservation.id}::uuid`);
   await tx.auditEvent.create({data:{organizationId:input.organizationId,actorUserId:context.userId,action:"INVENTORY_RESERVATION_CONSUMED",entityType:"MaterialLot",entityId:reservation.materialLotId,reason,metadata:{reservationId:reservation.id,transactionId:transaction.id,quantity:reservation.quantity,unitOfMeasure:reservation.unitOfMeasure}}});
   return{reservationId:reservation.id,transactionId:transaction.id};
  });
 }
 async evaluate(context:AuthorizationContext,organizationId:string){requireAuthorization(context,{organizationId,permission:"inventory.manage"});return db.$transaction(async tx=>{
  let expired=0,alerts=0;
  const expiredLots=await tx.$queryRaw<Array<{id:string;lotNumber:string}>>(Prisma.sql`SELECT id,"lotNumber" FROM "MaterialLot" WHERE "organizationId"=${organizationId}::uuid AND status='ACCEPTED' AND "expirationDate"<CURRENT_DATE FOR UPDATE`);
  for(const lot of expiredLots){await tx.$executeRaw(Prisma.sql`UPDATE "MaterialLot" SET status='EXPIRED',"updatedAt"=CURRENT_TIMESTAMP WHERE "organizationId"=${organizationId}::uuid AND id=${lot.id}::uuid`);await tx.$executeRaw(Prisma.sql`INSERT INTO "MaterialLotStatusChange" ("organizationId","materialLotId","fromStatus","toStatus",reason,"actorUserId") VALUES (${organizationId}::uuid,${lot.id}::uuid,'ACCEPTED'::"MaterialLotStatus",'EXPIRED'::"MaterialLotStatus",'Automatic expiration hard stop',NULL)`);await tx.$executeRaw(Prisma.sql`INSERT INTO "InventoryAutomationEvent" ("organizationId","eventType","materialLotId",level,"eventKey") VALUES (${organizationId}::uuid,'LOT_EXPIRED',${lot.id}::uuid,0,${`lot-expired:${lot.id}`}) ON CONFLICT DO NOTHING`);expired++;}
  const recipients=await tx.$queryRaw<Array<{userId:string}>>(Prisma.sql`SELECT DISTINCT ur."userId" FROM "UserRole" ur JOIN "RolePermission" rp ON rp."roleId"=ur."roleId" JOIN "Permission" p ON p.id=rp."permissionId" AND p.key='inventory.manage' JOIN "User" u ON u.id=ur."userId" AND u."organizationId"=ur."organizationId" AND u.state='ACTIVE' WHERE ur."organizationId"=${organizationId}::uuid`);
  const events=await tx.$queryRaw<Array<{id:string;thresholdId:string;openedAt:Date;materialId:string}>>(Prisma.sql`SELECT e.id,e."thresholdId",e."openedAt",t."materialId" FROM "InventoryLowStockEvent" e JOIN "InventoryLowStockThreshold" t ON t.id=e."thresholdId" WHERE e."organizationId"=${organizationId}::uuid AND e."resolvedAt" IS NULL`);
  for(const event of events){const ageDays=Math.floor((Date.now()-event.openedAt.getTime())/86400000);for(const level of [1,7,30])if(ageDays>=level){const inserted=await tx.$executeRaw(Prisma.sql`INSERT INTO "InventoryAutomationEvent" ("organizationId","eventType","lowStockEventId",level,"eventKey") VALUES (${organizationId}::uuid,'LOW_STOCK_ESCALATION',${event.id}::uuid,${level},${`low-stock:${event.id}:level:${level}`}) ON CONFLICT DO NOTHING`);if(inserted&&recipients.length){await tx.notificationOutbox.createMany({data:recipients.map(({userId})=>({organizationId,recipientUserId:userId,eventKey:`inventory-low-stock:${event.id}:level:${level}`,templateKey:"INVENTORY_LOW_STOCK_ESCALATION",payload:{lowStockEventId:event.id,materialId:event.materialId,level,ageDays}})),skipDuplicates:true});alerts+=recipients.length;}}}
  return{expiredLots:expired,notificationsQueued:alerts};
 });}
}