import type { AuthorizationContext } from "../security/authorization";
import { requireAuthorization } from "../security/authorization";

export class InventoryValidationError extends Error {}
export type MaterialRecord={id:string;organizationId:string;materialNumber:string;name:string;manufacturer:string|null;catalogNumber:string|null;description:string|null;status:"ACTIVE"|"INACTIVE";createdByUserId:string;createdAt:Date;updatedAt:Date};
export type MaterialLotStatus="RECEIVED"|"ACCEPTED"|"QUARANTINED"|"REJECTED"|"EXPIRED"|"RECALLED"|"DEPLETED";
export type MaterialLotRecord={id:string;organizationId:string;materialId:string;lotNumber:string;status:MaterialLotStatus;receivedAt:Date;expirationDate:Date|null;quantityReceived:string|null;unitOfMeasure:string|null;siteId:string|null;departmentId:string|null;evidenceFileId:string|null;receiptPostedAt:Date|null;createdByUserId:string;createdAt:Date;updatedAt:Date};
export type InventoryTransactionType="ADJUSTMENT_IN"|"ADJUSTMENT_OUT"|"CONSUMPTION";
export type InventoryTransactionRecord={id:string;organizationId:string;materialLotId:string;transactionType:string;quantity:string;unitOfMeasure:string;siteId:string|null;departmentId:string|null;reason:string;referenceKey:string|null;transferKey:string|null;actorUserId:string;occurredAt:Date;createdAt:Date};
export type InventoryBalanceRecord={organizationId:string;materialLotId:string;siteId:string|null;departmentId:string|null;quantityOnHand:string;unitOfMeasure:string;updatedAt:Date};
export type InventoryTransferResult={transferKey:string;outbound:InventoryTransactionRecord;inbound:InventoryTransactionRecord};
export interface InventoryStore{
 listMaterials(organizationId:string):Promise<MaterialRecord[]>;
 createMaterial(input:{organizationId:string;materialNumber:string;name:string;manufacturer:string|null;catalogNumber:string|null;description:string|null;actorUserId:string}):Promise<MaterialRecord>;
 listLots(organizationId:string,materialId?:string):Promise<MaterialLotRecord[]>;
 receiveLot(input:{organizationId:string;materialId:string;lotNumber:string;receivedAt:Date;expirationDate:Date|null;quantityReceived:number|null;unitOfMeasure:string|null;siteId:string|null;departmentId:string|null;evidenceFileId:string|null;actorUserId:string}):Promise<MaterialLotRecord>;
 transitionLot(input:{organizationId:string;lotId:string;status:MaterialLotStatus;reason:string;actorUserId:string}):Promise<MaterialLotRecord>;
 listBalances(organizationId:string,lotId?:string):Promise<InventoryBalanceRecord[]>;
 transact(input:{organizationId:string;lotId:string;transactionType:InventoryTransactionType;quantity:number;unitOfMeasure:string;siteId:string|null;departmentId:string|null;reason:string;referenceKey:string|null;occurredAt:Date;actorUserId:string}):Promise<InventoryTransactionRecord>;
 transfer(input:{organizationId:string;lotId:string;quantity:number;unitOfMeasure:string;fromSiteId:string|null;fromDepartmentId:string|null;toSiteId:string|null;toDepartmentId:string|null;reason:string;transferKey:string;occurredAt:Date;actorUserId:string}):Promise<InventoryTransferResult>;
}
export class InventoryService{
 constructor(private readonly store:InventoryStore){}
 listMaterials(context:AuthorizationContext,organizationId:string){requireAuthorization(context,{organizationId,permission:"inventory.read"});return this.store.listMaterials(organizationId);}
 createMaterial(context:AuthorizationContext,input:{organizationId:string;materialNumber:string;name:string;manufacturer?:string|null;catalogNumber?:string|null;description?:string|null}){requireAuthorization(context,{organizationId:input.organizationId,permission:"inventory.manage"});const materialNumber=input.materialNumber.trim(),name=input.name.trim();if(!materialNumber||materialNumber.length>80)throw new InventoryValidationError("Material number is required and must not exceed 80 characters");if(!name||name.length>240)throw new InventoryValidationError("Material name is required and must not exceed 240 characters");return this.store.createMaterial({...input,materialNumber,name,manufacturer:input.manufacturer?.trim()||null,catalogNumber:input.catalogNumber?.trim()||null,description:input.description?.trim()||null,actorUserId:context.userId});}
 listLots(context:AuthorizationContext,organizationId:string,materialId?:string){requireAuthorization(context,{organizationId,permission:"inventory.read"});return this.store.listLots(organizationId,materialId);}
 receiveLot(context:AuthorizationContext,input:{organizationId:string;materialId:string;lotNumber:string;receivedAt:Date;expirationDate?:Date|null;quantityReceived?:number|null;unitOfMeasure?:string|null;siteId?:string|null;departmentId?:string|null;evidenceFileId?:string|null}){requireAuthorization(context,{organizationId:input.organizationId,permission:"inventory.manage"});const lotNumber=input.lotNumber.trim();if(!lotNumber||lotNumber.length>120)throw new InventoryValidationError("Lot number is required and must not exceed 120 characters");if(Number.isNaN(input.receivedAt.getTime()))throw new InventoryValidationError("Received date is invalid");if(input.expirationDate&&Number.isNaN(input.expirationDate.getTime()))throw new InventoryValidationError("Expiration date is invalid");if(input.quantityReceived!=null&&input.quantityReceived<0)throw new InventoryValidationError("Quantity received cannot be negative");const unitOfMeasure=input.quantityReceived==null?null:input.unitOfMeasure?.trim()||null;if(input.quantityReceived!=null&&!unitOfMeasure)throw new InventoryValidationError("Unit of measure is required when quantity is recorded");return this.store.receiveLot({...input,lotNumber,expirationDate:input.expirationDate??null,quantityReceived:input.quantityReceived??null,unitOfMeasure,siteId:input.siteId??null,departmentId:input.departmentId??null,evidenceFileId:input.evidenceFileId??null,actorUserId:context.userId});}
 transitionLot(context:AuthorizationContext,input:{organizationId:string;lotId:string;status:MaterialLotStatus;reason:string}){requireAuthorization(context,{organizationId:input.organizationId,permission:"inventory.manage"});const reason=input.reason.trim();if(!reason||reason.length>2000)throw new InventoryValidationError("Lot status reason is required and must not exceed 2000 characters");return this.store.transitionLot({...input,reason,actorUserId:context.userId});}
 listBalances(context:AuthorizationContext,organizationId:string,lotId?:string){requireAuthorization(context,{organizationId,permission:"inventory.read"});return this.store.listBalances(organizationId,lotId);}
 transact(context:AuthorizationContext,input:{organizationId:string;lotId:string;transactionType:InventoryTransactionType;quantity:number;unitOfMeasure:string;siteId?:string|null;departmentId?:string|null;reason:string;referenceKey?:string|null;occurredAt:Date}){requireAuthorization(context,{organizationId:input.organizationId,permission:"inventory.manage"});if(!Number.isFinite(input.quantity)||input.quantity<=0)throw new InventoryValidationError("Inventory quantity must be greater than zero");const unitOfMeasure=input.unitOfMeasure.trim(),reason=input.reason.trim(),referenceKey=input.referenceKey?.trim()||null;if(!unitOfMeasure||unitOfMeasure.length>80)throw new InventoryValidationError("Inventory unit of measure is required and must not exceed 80 characters");if(!reason||reason.length>2000)throw new InventoryValidationError("Inventory transaction reason is required and must not exceed 2000 characters");if(referenceKey&&referenceKey.length>240)throw new InventoryValidationError("Inventory reference key must not exceed 240 characters");if(Number.isNaN(input.occurredAt.getTime()))throw new InventoryValidationError("Inventory transaction time is invalid");return this.store.transact({...input,unitOfMeasure,reason,referenceKey,siteId:input.siteId??null,departmentId:input.departmentId??null,actorUserId:context.userId});}
 transfer(context:AuthorizationContext,input:{organizationId:string;lotId:string;quantity:number;unitOfMeasure:string;fromSiteId?:string|null;fromDepartmentId?:string|null;toSiteId?:string|null;toDepartmentId?:string|null;reason:string;transferKey:string;occurredAt:Date}){requireAuthorization(context,{organizationId:input.organizationId,permission:"inventory.manage"});if(!Number.isFinite(input.quantity)||input.quantity<=0)throw new InventoryValidationError("Transfer quantity must be greater than zero");const unitOfMeasure=input.unitOfMeasure.trim(),reason=input.reason.trim(),transferKey=input.transferKey.trim();if(!unitOfMeasure||unitOfMeasure.length>80)throw new InventoryValidationError("Transfer unit of measure is required and must not exceed 80 characters");if(!reason||reason.length>2000)throw new InventoryValidationError("Transfer reason is required and must not exceed 2000 characters");if(!transferKey||transferKey.length>240)throw new InventoryValidationError("Transfer key is required and must not exceed 240 characters");const fromSiteId=input.fromSiteId??null,fromDepartmentId=input.fromDepartmentId??null,toSiteId=input.toSiteId??null,toDepartmentId=input.toDepartmentId??null;if(fromSiteId===toSiteId&&fromDepartmentId===toDepartmentId)throw new InventoryValidationError("Transfer source and destination must differ");if(Number.isNaN(input.occurredAt.getTime()))throw new InventoryValidationError("Transfer time is invalid");return this.store.transfer({...input,unitOfMeasure,reason,transferKey,fromSiteId,fromDepartmentId,toSiteId,toDepartmentId,actorUserId:context.userId});}
}