import { Prisma } from "@prisma/client";
import type { AuthorizationContext } from "../security/authorization";
import { requireAuthorization } from "../security/authorization";
import { db } from "../db";
import { InventoryValidationError } from "./inventory";

export type RecallImpactDisposition="NO_IMPACT"|"POTENTIAL_IMPACT"|"CONFIRMED_IMPACT";

export class InventoryRecallControlService {
 async dispositionImpact(context:AuthorizationContext,input:{organizationId:string;impactId:string;disposition:RecallImpactDisposition;reason:string}){
  requireAuthorization(context,{organizationId:input.organizationId,permission:"inventory.manage"});const reason=input.reason.trim();if(!reason)throw new InventoryValidationError("Recall impact disposition reason is required");return db.$transaction(async tx=>{const impact=(await tx.$queryRaw<Array<{id:string;materialRecallId:string;materialLotId:string}>>(Prisma.sql`SELECT id,"materialRecallId","materialLotId" FROM "MaterialRecallImpact" WHERE "organizationId"=${input.organizationId}::uuid AND id=${input.impactId}::uuid`))[0];if(!impact)throw new InventoryValidationError("Recall impact not found");const closed=await tx.$queryRaw<Array<{id:string}>>(Prisma.sql`SELECT id FROM "MaterialRecallImpactActionEvent" WHERE "organizationId"=${input.organizationId}::uuid AND "materialRecallImpactId"=${input.impactId}::uuid AND action='CLOSURE' LIMIT 1`);if(closed.length)throw new InventoryValidationError("Closed recall impact cannot be redispositioned");const row=(await tx.$queryRaw<Array<{id:string}>>(Prisma.sql`INSERT INTO "MaterialRecallImpactActionEvent" ("organizationId","materialRecallImpactId",action,disposition,reason,"actorUserId") VALUES (${input.organizationId}::uuid,${input.impactId}::uuid,'DISPOSITION'::"MaterialRecallImpactAction",${input.disposition}::"MaterialRecallImpactDisposition",${reason},${context.userId}::uuid) RETURNING id`))[0];if(!row)throw new InventoryValidationError("Recall impact disposition could not be recorded");await tx.auditEvent.create({data:{organizationId:input.organizationId,actorUserId:context.userId,action:"MATERIAL_RECALL_IMPACT_DISPOSITIONED",entityType:"MaterialRecallImpact",entityId:input.impactId,reason,metadata:{materialRecallId:impact.materialRecallId,materialLotId:impact.materialLotId,disposition:input.disposition,actionEventId:row.id}}});return{id:row.id};});
 }
 async closeImpact(context:AuthorizationContext,input:{organizationId:string;impactId:string;reason:string}){
  requireAuthorization(context,{organizationId:input.organizationId,permission:"inventory.manage"});const reason=input.reason.trim();if(!reason)throw new InventoryValidationError("Recall impact closure reason is required");return db.$transaction(async tx=>{const impact=(await tx.$queryRaw<Array<{id:string;materialRecallId:string;materialLotId:string}>>(Prisma.sql`SELECT id,"materialRecallId","materialLotId" FROM "MaterialRecallImpact" WHERE "organizationId"=${input.organizationId}::uuid AND id=${input.impactId}::uuid`))[0];if(!impact)throw new InventoryValidationError("Recall impact not found");const latest=await tx.$queryRaw<Array<{action:string}>>(Prisma.sql`SELECT action FROM "MaterialRecallImpactActionEvent" WHERE "organizationId"=${input.organizationId}::uuid AND "materialRecallImpactId"=${input.impactId}::uuid ORDER BY "createdAt" DESC LIMIT 1`);if(!latest.length||latest[0].action!=="DISPOSITION")throw new InventoryValidationError("Recall impact requires a disposition before closure");const row=(await tx.$queryRaw<Array<{id:string}>>(Prisma.sql`INSERT INTO "MaterialRecallImpactActionEvent" ("organizationId","materialRecallImpactId",action,disposition,reason,"actorUserId") VALUES (${input.organizationId}::uuid,${input.impactId}::uuid,'CLOSURE'::"MaterialRecallImpactAction",NULL,${reason},${context.userId}::uuid) RETURNING id`))[0];if(!row)throw new InventoryValidationError("Recall impact closure could not be recorded");await tx.auditEvent.create({data:{organizationId:input.organizationId,actorUserId:context.userId,action:"MATERIAL_RECALL_IMPACT_CLOSED",entityType:"MaterialRecallImpact",entityId:input.impactId,reason,metadata:{materialRecallId:impact.materialRecallId,materialLotId:impact.materialLotId,actionEventId:row.id}}});return{id:row.id};});
 }
 async evaluateEscalations(context:AuthorizationContext,organizationId:string){requireAuthorization(context,{organizationId,permission:"inventory.manage"});return this.evaluateOrganization(organizationId);}
 async evaluateOrganization(organizationId:string){return db.$transaction(async tx=>{let notificationsQueued=0,eventsCreated=0;const recalls=await tx.$queryRaw<Array<{id:string;externalReference:string;manufacturer:string;createdAt:Date}>>(Prisma.sql`SELECT r.id,r."externalReference",r.manufacturer,r."createdAt" FROM "MaterialRecall" r WHERE r."organizationId"=${organizationId}::uuid AND EXISTS (SELECT 1 FROM "MaterialRecallImpact" i WHERE i."organizationId"=r."organizationId" AND i."materialRecallId"=r.id AND NOT EXISTS (SELECT 1 FROM "MaterialRecallImpactActionEvent" a WHERE a."organizationId"=i."organizationId" AND a."materialRecallImpactId"=i.id AND a.action='CLOSURE'))`);const recipients=await tx.$queryRaw<Array<{userId:string}>>(Prisma.sql`SELECT DISTINCT ur."userId" FROM "UserRole" ur JOIN "RolePermission" rp ON rp."roleId"=ur."roleId" JOIN "Permission" p ON p.id=rp."permissionId" AND p.key='inventory.manage' JOIN "User" u ON u.id=ur."userId" AND u."organizationId"=ur."organizationId" AND u.state='ACTIVE' WHERE ur."organizationId"=${organizationId}::uuid AND ur."scopeType"='ORGANIZATION' AND ur."scopeId" IS NULL`);for(const recall of recalls){const ageDays=Math.floor((Date.now()-recall.createdAt.getTime())/86400000);for(const level of [0,1,7,30]){if(ageDays<level)continue;const eventKey=`material-recall:${recall.id}:level:${level}`;const inserted=await tx.$executeRaw(Prisma.sql`INSERT INTO "MaterialRecallEscalationEvent" ("organizationId","materialRecallId",level,"eventKey") VALUES (${organizationId}::uuid,${recall.id}::uuid,${level},${eventKey}) ON CONFLICT DO NOTHING`);if(!inserted)continue;eventsCreated++;if(recipients.length){await tx.notificationOutbox.createMany({data:recipients.map(({userId})=>({organizationId,recipientUserId:userId,eventKey:`inventory-${eventKey}`,templateKey:level===0?"INVENTORY_RECALL_OPENED":"INVENTORY_RECALL_ESCALATION",payload:{materialRecallId:recall.id,externalReference:recall.externalReference,manufacturer:recall.manufacturer,level,ageDays}})),skipDuplicates:true});notificationsQueued+=recipients.length;}}}return{eventsCreated,notificationsQueued};});}
}
