import { NextRequest,NextResponse } from "next/server";
import { z } from "zod";
import { authenticateRequest,AuthenticationRequiredError } from "@/lib/security/authenticated-request";
import { EquipmentService,EquipmentValidationError } from "@/lib/equipment/equipment";
import { PrismaEquipmentStore } from "@/lib/equipment/equipment-store";
const service=new EquipmentService(new PrismaEquipmentStore());
const lifecycleSchema=z.object({operation:z.literal("TRANSITION").optional(),status:z.enum(["PLANNED","ACTIVE","OUT_OF_SERVICE","RETIRED"]),reason:z.string().max(1000)});
const scheduleSchema=z.object({operation:z.literal("CORRECT_SCHEDULE"),nextCalibrationDueAt:z.string().nullable(),nextMaintenanceDueAt:z.string().nullable(),reason:z.string().max(1000)});
function parseDate(value:string|null){return value?new Date(`${value}T12:00:00.000Z`):null;}
export async function PATCH(request:NextRequest,{params}:{params:Promise<{equipmentId:string}>}){try{const context=await authenticateRequest(request);const {equipmentId}=await params;const body:unknown=await request.json();if(typeof body==="object"&&body!==null&&"operation" in body&&(body as {operation?:unknown}).operation==="CORRECT_SCHEDULE"){const input=scheduleSchema.parse(body);return NextResponse.json({data:await service.correctSchedule(context,{organizationId:context.organizationId,equipmentId,nextCalibrationDueAt:parseDate(input.nextCalibrationDueAt),nextMaintenanceDueAt:parseDate(input.nextMaintenanceDueAt),reason:input.reason})});}const input=lifecycleSchema.parse(body);return NextResponse.json({data:await service.transition(context,{organizationId:context.organizationId,equipmentId,status:input.status,reason:input.reason})});}catch(error){if(error instanceof AuthenticationRequiredError)return NextResponse.json({error:"Authentication required"},{status:401});if(error instanceof z.ZodError)return NextResponse.json({error:"Invalid equipment update request"},{status:422});if(error instanceof EquipmentValidationError)return NextResponse.json({error:error.message},{status:409});if(error instanceof Error&&error.message==="Access denied")return NextResponse.json({error:"Access denied"},{status:403});return NextResponse.json({error:"Equipment update operation failed"},{status:500});}}
