"use client";
import { useEffect,useState } from "react";
type Analytics={total:number;active:number;outOfService:number;retired:number;activeHolds:number;calibrationDue30:number;maintenanceDue30:number;serviceFailures90:number};
type Item={id:string;equipmentNumber:string;name:string;status:string;nextCalibrationDueAt:string|null;nextMaintenanceDueAt:string|null;activeHoldCount:number;usable:boolean};
export function EquipmentManagementWorkspace({canManage}:{canManage:boolean}){
 const [analytics,setAnalytics]=useState<Analytics|null>(null),[equipment,setEquipment]=useState<Item[]>([]),[error,setError]=useState("");
 const [selected,setSelected]=useState(""),[description,setDescription]=useState(""),[provider,setProvider]=useState(""),[outcome,setOutcome]=useState("COMPLETED"),[message,setMessage]=useState("");
 async function refresh(){setError("");const r=await fetch("/api/equipment/operations",{cache:"no-store"});if(!r.ok){setError("Unable to load equipment operations");return;}const j=await r.json();setAnalytics(j.data.analytics);setEquipment(j.data.equipment);setSelected(current=>current||j.data.equipment[0]?.id||"");}
 useEffect(()=>{let cancelled=false;async function initialLoad(){const r=await fetch("/api/equipment/operations",{cache:"no-store"});if(cancelled)return;if(!r.ok){setError("Unable to load equipment operations");return;}const j=await r.json();if(cancelled)return;setAnalytics(j.data.analytics);setEquipment(j.data.equipment);setSelected(j.data.equipment[0]?.id??"");}void initialLoad();return()=>{cancelled=true;};},[]);
 async function recordService(e:React.FormEvent){e.preventDefault();if(!selected)return;setMessage("");const r=await fetch(`/api/equipment/${selected}/service`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({servicedAt:new Date().toISOString(),provider,description,outcome})});const j=await r.json();setMessage(r.ok?"Service record saved and audited.":j.error??"Service record failed");if(r.ok){setDescription("");setProvider("");await refresh();}}
 return <section className="workspace-section"><div className="workspace-heading"><div><p className="eyebrow">Laboratory operations</p><h2>Equipment management</h2><p>Governed usability, compliance holds, service history, and management indicators.</p></div></div>
 {error&&<p className="status-error">{error}</p>}
 {analytics&&<div className="stat-grid"><article><strong>{analytics.total}</strong><span>Total equipment</span></article><article><strong>{analytics.active}</strong><span>Active</span></article><article><strong>{analytics.activeHolds}</strong><span>Active compliance holds</span></article><article><strong>{analytics.calibrationDue30}</strong><span>Calibration due ≤30d</span></article><article><strong>{analytics.maintenanceDue30}</strong><span>Maintenance due ≤30d</span></article><article><strong>{analytics.serviceFailures90}</strong><span>Service failures / 90d</span></article></div>}
 <div className="table-wrap"><table><thead><tr><th>Equipment</th><th>Status</th><th>Usability</th><th>Calibration due</th><th>Maintenance due</th><th>Holds</th></tr></thead><tbody>{equipment.map(x=><tr key={x.id}><td><button type="button" className="link-button" onClick={()=>setSelected(x.id)}>{x.equipmentNumber} — {x.name}</button></td><td>{x.status}</td><td><strong>{x.usable?"USABLE":"NOT USABLE"}</strong></td><td>{x.nextCalibrationDueAt?.slice(0,10)??"—"}</td><td>{x.nextMaintenanceDueAt?.slice(0,10)??"—"}</td><td>{x.activeHoldCount}</td></tr>)}</tbody></table></div>
 {canManage&&<form className="card form-stack" onSubmit={recordService}><h3>Record service / repair evidence</h3><label>Equipment<select value={selected} onChange={e=>setSelected(e.target.value)}>{equipment.map(x=><option key={x.id} value={x.id}>{x.equipmentNumber} — {x.name}</option>)}</select></label><label>Provider<input value={provider} onChange={e=>setProvider(e.target.value)} maxLength={240}/></label><label>Outcome<select value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="COMPLETED">Completed</option><option value="FAILED">Failed</option></select></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={5000} required/></label><button type="submit">Save audited service record</button>{message&&<p>{message}</p>}</form>}
 </section>;
}
