"use client";
import { useEffect,useState } from "react";
type Analytics={total:number;active:number;outOfService:number;retired:number;activeHolds:number;calibrationDue30:number;maintenanceDue30:number;serviceFailures90:number};
type Item={id:string;equipmentNumber:string;name:string;status:string;nextCalibrationDueAt:string|null;nextMaintenanceDueAt:string|null;activeHoldCount:number;usable:boolean};
export function EquipmentManagementWorkspace({canManage}:{canManage:boolean}){
 const [analytics,setAnalytics]=useState<Analytics|null>(null),[equipment,setEquipment]=useState<Item[]>([]),[error,setError]=useState("");
 const [selected,setSelected]=useState(""),[description,setDescription]=useState(""),[provider,setProvider]=useState(""),[outcome,setOutcome]=useState("COMPLETED"),[message,setMessage]=useState("");
 const [equipmentNumber,setEquipmentNumber]=useState(""),[name,setName]=useState(""),[manufacturer,setManufacturer]=useState(""),[model,setModel]=useState(""),[serialNumber,setSerialNumber]=useState(""),[receivedAt,setReceivedAt]=useState("");
 const [calibrationRequired,setCalibrationRequired]=useState(false),[calibrationIntervalDays,setCalibrationIntervalDays]=useState(""),[nextCalibrationDueAt,setNextCalibrationDueAt]=useState("");
 const [maintenanceRequired,setMaintenanceRequired]=useState(false),[maintenanceIntervalDays,setMaintenanceIntervalDays]=useState(""),[nextMaintenanceDueAt,setNextMaintenanceDueAt]=useState("");
 const [registrationMessage,setRegistrationMessage]=useState("");
 async function refresh(){setError("");const r=await fetch("/api/equipment/operations",{cache:"no-store"});if(!r.ok){setError("Unable to load equipment operations");return;}const j=await r.json();setAnalytics(j.data.analytics);setEquipment(j.data.equipment);setSelected(current=>current||j.data.equipment[0]?.id||"");}
 useEffect(()=>{let cancelled=false;async function initialLoad(){const r=await fetch("/api/equipment/operations",{cache:"no-store"});if(cancelled)return;if(!r.ok){setError("Unable to load equipment operations");return;}const j=await r.json();if(cancelled)return;setAnalytics(j.data.analytics);setEquipment(j.data.equipment);setSelected(j.data.equipment[0]?.id??"");}void initialLoad();return()=>{cancelled=true;};},[]);
 async function registerEquipment(e:React.FormEvent){e.preventDefault();setRegistrationMessage("");const payload={equipmentNumber,name,manufacturer:manufacturer||null,model:model||null,serialNumber:serialNumber||null,receivedAt:receivedAt||null,calibrationRequired,calibrationIntervalDays:calibrationRequired&&calibrationIntervalDays?Number(calibrationIntervalDays):null,nextCalibrationDueAt:calibrationRequired&&nextCalibrationDueAt?nextCalibrationDueAt:null,maintenanceRequired,maintenanceIntervalDays:maintenanceRequired&&maintenanceIntervalDays?Number(maintenanceIntervalDays):null,nextMaintenanceDueAt:maintenanceRequired&&nextMaintenanceDueAt?nextMaintenanceDueAt:null};const r=await fetch("/api/equipment",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const j=await r.json().catch(()=>null);setRegistrationMessage(r.ok?"Equipment registered with governed audit history.":j?.error??"Equipment registration failed");if(r.ok){setEquipmentNumber("");setName("");setManufacturer("");setModel("");setSerialNumber("");setReceivedAt("");setCalibrationRequired(false);setCalibrationIntervalDays("");setNextCalibrationDueAt("");setMaintenanceRequired(false);setMaintenanceIntervalDays("");setNextMaintenanceDueAt("");await refresh();}}
 async function recordService(e:React.FormEvent){e.preventDefault();if(!selected)return;setMessage("");const r=await fetch(`/api/equipment/${selected}/service`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({servicedAt:new Date().toISOString(),provider,description,outcome})});const j=await r.json();setMessage(r.ok?"Service record saved and audited.":j.error??"Service record failed");if(r.ok){setDescription("");setProvider("");await refresh();}}
 return <section className="workspace-section"><div className="workspace-heading"><div><p className="eyebrow">Laboratory operations</p><h2>Equipment management</h2><p>Governed usability, compliance holds, service history, and management indicators.</p></div></div>
 {error&&<p className="status-error">{error}</p>}
 {analytics&&<div className="stat-grid"><article><strong>{analytics.total}</strong><span>Total equipment</span></article><article><strong>{analytics.active}</strong><span>Active</span></article><article><strong>{analytics.activeHolds}</strong><span>Active compliance holds</span></article><article><strong>{analytics.calibrationDue30}</strong><span>Calibration due ≤30d</span></article><article><strong>{analytics.maintenanceDue30}</strong><span>Maintenance due ≤30d</span></article><article><strong>{analytics.serviceFailures90}</strong><span>Service failures / 90d</span></article></div>}
 {canManage&&<form className="card admin-form" onSubmit={registerEquipment}><h3 style={{gridColumn:"1 / -1"}}>Register equipment</h3><label>Equipment number<input required value={equipmentNumber} onChange={e=>setEquipmentNumber(e.target.value)} maxLength={80}/></label><label>Equipment name<input required value={name} onChange={e=>setName(e.target.value)} maxLength={240}/></label><label>Manufacturer<input value={manufacturer} onChange={e=>setManufacturer(e.target.value)} maxLength={240}/></label><label>Model<input value={model} onChange={e=>setModel(e.target.value)} maxLength={240}/></label><label>Serial number<input value={serialNumber} onChange={e=>setSerialNumber(e.target.value)} maxLength={240}/></label><label>Received date<input type="date" value={receivedAt} onChange={e=>setReceivedAt(e.target.value)}/></label><label><input type="checkbox" checked={calibrationRequired} onChange={e=>setCalibrationRequired(e.target.checked)}/> Calibration required</label>{calibrationRequired&&<><label>Calibration interval (days)<input required type="number" min={1} value={calibrationIntervalDays} onChange={e=>setCalibrationIntervalDays(e.target.value)}/></label><label>Next calibration due<input type="date" value={nextCalibrationDueAt} onChange={e=>setNextCalibrationDueAt(e.target.value)}/></label></>}<label><input type="checkbox" checked={maintenanceRequired} onChange={e=>setMaintenanceRequired(e.target.checked)}/> Maintenance required</label>{maintenanceRequired&&<><label>Maintenance interval (days)<input required type="number" min={1} value={maintenanceIntervalDays} onChange={e=>setMaintenanceIntervalDays(e.target.value)}/></label><label>Next maintenance due<input type="date" value={nextMaintenanceDueAt} onChange={e=>setNextMaintenanceDueAt(e.target.value)}/></label></>}<button type="submit">Register equipment</button>{registrationMessage&&<p style={{gridColumn:"1 / -1"}}>{registrationMessage}</p>}</form>}
 <div className="table-wrap"><table><thead><tr><th>Equipment</th><th>Status</th><th>Usability</th><th>Calibration due</th><th>Maintenance due</th><th>Holds</th></tr></thead><tbody>{equipment.map(x=><tr key={x.id}><td><button type="button" className="link-button" onClick={()=>setSelected(x.id)}>{x.equipmentNumber} — {x.name}</button></td><td>{x.status}</td><td><strong>{x.usable?"USABLE":"NOT USABLE"}</strong></td><td>{x.nextCalibrationDueAt?.slice(0,10)??"—"}</td><td>{x.nextMaintenanceDueAt?.slice(0,10)??"—"}</td><td>{x.activeHoldCount}</td></tr>)}{!equipment.length&&<tr><td colSpan={6}>No equipment has been registered.</td></tr>}</tbody></table></div>
 {canManage&&<form className="card form-stack" onSubmit={recordService}><h3>Record service / repair evidence</h3><label>Equipment<select value={selected} onChange={e=>setSelected(e.target.value)} disabled={!equipment.length}>{equipment.length?<>{equipment.map(x=><option key={x.id} value={x.id}>{x.equipmentNumber} — {x.name}</option>)}</>:<option value="">Register equipment first</option>}</select></label><label>Provider<input value={provider} onChange={e=>setProvider(e.target.value)} maxLength={240}/></label><label>Outcome<select value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="COMPLETED">Completed</option><option value="FAILED">Failed</option></select></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={5000} required/></label><button type="submit" disabled={!selected}>Save audited service record</button>{message&&<p>{message}</p>}</form>}
 </section>;
}
