"use client";
import { useEffect,useMemo,useState } from "react";

type Hold={id:string;kind:"CALIBRATION_OVERDUE"|"MAINTENANCE_OVERDUE";dueAt:string;detectedAt:string;clearedAt:string|null;clearanceReason:string|null};
type Disposition="NO_IMPACT"|"POTENTIAL_IMPACT"|"CONFIRMED_IMPACT";

export function EquipmentCompliancePanel({equipmentId,canManage,onChanged}:{equipmentId:string;canManage:boolean;onChanged:()=>Promise<void>}){
 const [holds,setHolds]=useState<Hold[]>([]),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [holdId,setHoldId]=useState(""),[disposition,setDisposition]=useState<Disposition>("NO_IMPACT"),[scopeSummary,setScopeSummary]=useState(""),[rationale,setRationale]=useState(""),[clearanceReason,setClearanceReason]=useState("");
 const activeHolds=useMemo(()=>holds.filter(hold=>!hold.clearedAt),[holds]);
 async function load(){const r=await fetch(`/api/equipment/${equipmentId}/compliance`,{cache:"no-store"});const j=await r.json().catch(()=>null);if(!r.ok){setError(j?.error??"Unable to load equipment compliance holds");return;}setError("");setHolds(j?.data??[]);setHoldId(current=>current&&j?.data?.some((hold:Hold)=>hold.id===current&&!hold.clearedAt)?current:(j?.data??[]).find((hold:Hold)=>!hold.clearedAt)?.id??"");}
 useEffect(()=>{let cancelled=false;async function initialLoad(){const r=await fetch(`/api/equipment/${equipmentId}/compliance`,{cache:"no-store"});const j=await r.json().catch(()=>null);if(cancelled)return;if(!r.ok){setError(j?.error??"Unable to load equipment compliance holds");return;}const loaded:Hold[]=j?.data??[];setHolds(loaded);setHoldId(loaded.find(hold=>!hold.clearedAt)?.id??"");}void initialLoad();return()=>{cancelled=true;};},[equipmentId]);
 async function assess(e:React.FormEvent){e.preventDefault();if(!holdId)return;setMessage("");const r=await fetch(`/api/equipment/${equipmentId}/compliance`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"ASSESS_IMPACT",holdId,disposition,scopeSummary,rationale})});const j=await r.json().catch(()=>null);setMessage(r.ok?(j?.data?.qualityEventId?"Impact assessment recorded and quality event created.":"Impact assessment recorded and audited."):j?.error??"Impact assessment failed");if(r.ok){setScopeSummary("");setRationale("");await load();await onChanged();}}
 async function clear(e:React.FormEvent){e.preventDefault();if(!holdId)return;setMessage("");const r=await fetch(`/api/equipment/${equipmentId}/compliance`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"CLEAR_HOLD",holdId,reason:clearanceReason})});const j=await r.json().catch(()=>null);setMessage(r.ok?"Compliance hold cleared with audit evidence.":j?.error??"Compliance hold could not be cleared");if(r.ok){setClearanceReason("");await load();await onChanged();}}
 return <section className="form-stack"><h3>Compliance holds & impact assessment</h3><p>Overdue required calibration or maintenance creates a system compliance hold. An active hold makes otherwise-active equipment not usable until current compliance evidence supports clearance.</p>{error&&<p className="status-error">{error}</p>}{message&&<p role="status">{message}</p>}{holds.length?<ul>{holds.map(hold=><li key={hold.id}><strong>{hold.kind}</strong> · due {hold.dueAt.slice(0,10)} · detected {hold.detectedAt.slice(0,10)} · {hold.clearedAt?`CLEARED ${hold.clearedAt.slice(0,10)}`:"ACTIVE"}{hold.clearanceReason?` — ${hold.clearanceReason}`:""}</li>)}</ul>:<p>No compliance holds recorded.</p>}{canManage&&activeHolds.length>0&&<><label>Active hold<select value={holdId} onChange={e=>setHoldId(e.target.value)}>{activeHolds.map(hold=><option key={hold.id} value={hold.id}>{hold.kind} · due {hold.dueAt.slice(0,10)}</option>)}</select></label><form className="form-stack" onSubmit={assess}><h3>Record impact assessment</h3><label>Disposition<select value={disposition} onChange={e=>setDisposition(e.target.value as Disposition)}><option value="NO_IMPACT">No impact</option><option value="POTENTIAL_IMPACT">Potential impact</option><option value="CONFIRMED_IMPACT">Confirmed impact</option></select></label><label>Affected scope<textarea required maxLength={5000} value={scopeSummary} onChange={e=>setScopeSummary(e.target.value)}/></label><label>Assessment rationale<textarea required maxLength={5000} value={rationale} onChange={e=>setRationale(e.target.value)}/></label><button type="submit" disabled={!holdId||!scopeSummary.trim()||!rationale.trim()}>Record impact assessment</button></form><form className="form-stack" onSubmit={clear}><h3>Clear compliance hold</h3><p>Clearance is accepted only after newer calibration or maintenance evidence advances the applicable due date.</p><label>Required clearance reason<textarea required maxLength={1000} value={clearanceReason} onChange={e=>setClearanceReason(e.target.value)}/></label><button type="submit" disabled={!holdId||!clearanceReason.trim()}>Clear compliance hold</button></form></>}
 </section>;
}
