"use client";

import { useState, type FormEvent } from "react";

type Policy = { id: string; recordType: string; jurisdiction: string | null; retentionDays: number; active: boolean };
type Hold = { id: string; entityType: string; entityId: string; reason: string; status: string; createdAt: string; releasedAt: string | null; releaseReason: string | null };
type Payload = { policies: Policy[]; holds: Hold[] };

export function RetentionAdministration() {
  const [open, setOpen] = useState(false), [data, setData] = useState<Payload | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function load() { setBusy(true); setError(""); const response = await fetch("/api/retention"); const body = await response.json().catch(() => null); setBusy(false); if (!response.ok) { setError(response.status === 403 ? "Retention administration access required." : body?.error || "Unable to load retention controls."); return; } setData(body.data); }
  async function command(payload: unknown) { setBusy(true); setError(""); const response = await fetch("/api/retention", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json().catch(() => null); setBusy(false); if (!response.ok) { setError(body?.error || "Retention change failed."); return false; } await load(); return true; }
  async function addPolicy(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); if (await command({ operation: "CREATE_POLICY", recordType: String(form.get("recordType")), jurisdiction: String(form.get("jurisdiction") || "") || null, retentionDays: Number(form.get("retentionDays")) })) event.currentTarget.reset(); }
  async function addHold(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); if (await command({ operation: "CREATE_HOLD", entityType: String(form.get("entityType")), entityId: String(form.get("entityId")), reason: String(form.get("reason")) })) event.currentTarget.reset(); }
  return <><button type="button" style={{ position: "fixed", right: 1240, bottom: 24, zIndex: 80 }} onClick={async () => { setOpen(true); await load(); }}>Retention & holds</button>{open && <div className="modal-backdrop" role="presentation"><div className="modal detail-modal" role="dialog" aria-modal="true"><div className="modal-head"><div><h2>Retention & legal holds</h2><p>Govern record retention and preservation without destructive deletion.</p></div><button aria-label="Close retention administration" onClick={() => setOpen(false)}>×</button></div><div className="detail-body">{error && <div className="detail-error" role="alert">{error}</div>}<div className="template-layout"><form className="approval-box" onSubmit={addPolicy}><strong>Create retention policy</strong><label>Record type<input name="recordType" required maxLength={80} placeholder="FileObject" /></label><label>Jurisdiction<input name="jurisdiction" maxLength={120} /></label><label>Retention days<input name="retentionDays" type="number" min={1} max={36500} required /></label><button className="primary-button" disabled={busy}>Create policy</button></form><form className="approval-box" onSubmit={addHold}><strong>Place legal hold</strong><label>Record type<select name="entityType"><option>Document</option><option>DocumentVersion</option><option>FileObject</option></select></label><label>Record ID<input name="entityId" required /></label><label>Reason<textarea name="reason" required maxLength={500} /></label><button className="primary-button" disabled={busy}>Place hold</button></form></div><h3>Policies</h3>{data?.policies.map((p) => <div key={p.id}>{p.recordType} · {p.retentionDays} days · {p.jurisdiction || "All jurisdictions"} · {p.active ? "Active" : "Inactive"}</div>)}<h3>Legal holds</h3>{data?.holds.map((h) => <div key={h.id} style={{ marginTop: 8 }}>{h.entityType} {h.entityId.slice(0, 8)} · {h.status} · {h.reason}{h.status === "ACTIVE" && <button disabled={busy} onClick={() => { const reason = window.prompt("Release reason"); if (reason) void command({ operation: "RELEASE_HOLD", holdId: h.id, reason }); }}>Release</button>}</div>)}</div></div></div>}</>;
}
