import { NextRequest,NextResponse } from "next/server";
import { z } from "zod";
import { authenticateRequest,AuthenticationRequiredError } from "@/lib/security/authenticated-request";
import { ProcurementService } from "@/lib/inventory/procurement";
import { InventoryValidationError } from "@/lib/inventory/inventory";
const service=new ProcurementService();
const schema=z.discriminatedUnion("action",[
 z.object({action:z.literal("create_supplier"),supplierNumber:z.string().max(80),name:z.string().max(240),contactName:z.string().max(240).nullish(),contactEmail:z.string().max(320).nullish(),contactPhone:z.string().max(80).nullish(),notes:z.string().max(5000).nullish()}),
 z.object({action:z.literal("create_order"),purchaseOrderNumber:z.string().max(120),supplierId:z.string().uuid(),expectedAt:z.coerce.date().nullish(),notes:z.string().max(5000).nullish(),lines:z.array(z.object({materialId:z.string().uuid(),quantityOrdered:z.number().positive(),unitOfMeasure:z.string().max(80),unitPrice:z.number().nonnegative().nullish()})).min(1)}),
 z.object({action:z.literal("transition"),purchaseOrderId:z.string().uuid(),toStatus:z.enum(["SUBMITTED","APPROVED","ORDERED","PARTIALLY_RECEIVED","RECEIVED","CANCELLED"]),reason:z.string().max(2000)}),
 z.object({action:z.literal("receipt"),purchaseOrderLineId:z.string().uuid(),materialLotId:z.string().uuid(),quantityReceived:z.number().positive(),unitOfMeasure:z.string().max(80)})
]);
export async function GET(request:NextRequest){try{const context=await authenticateRequest(request);return NextResponse.json({data:await service.listSuppliers(context,context.organizationId)});}catch(error){if(error instanceof AuthenticationRequiredError)return NextResponse.json({error:"Authentication required"},{status:401});return NextResponse.json({error:"Unable to load procurement data"},{status:500});}}
export async function POST(request:NextRequest){try{const context=await authenticateRequest(request);const input=schema.parse(await request.json());if(input.action==="create_supplier")return NextResponse.json({data:await service.createSupplier(context,{organizationId:context.organizationId,...input})},{status:201});if(input.action==="create_order")return NextResponse.json({data:await service.createPurchaseOrder(context,{organizationId:context.organizationId,...input})},{status:201});if(input.action==="transition")return NextResponse.json({data:await service.transition(context,{organizationId:context.organizationId,...input})});return NextResponse.json({data:await service.recordReceipt(context,{organizationId:context.organizationId,...input})},{status:201});}catch(error){if(error instanceof AuthenticationRequiredError)return NextResponse.json({error:"Authentication required"},{status:401});if(error instanceof z.ZodError)return NextResponse.json({error:"Invalid procurement request"},{status:422});if(error instanceof InventoryValidationError)return NextResponse.json({error:error.message},{status:409});return NextResponse.json({error:"Procurement operation failed"},{status:500});}}